import chalk from 'chalk';
import { InvalidArgumentError } from 'commander';
import { handleProxyAction } from '../lib/proxy.js';
import { connectToDeviceConsole } from '../lib/console.js';
import { getDeviceStatus, formatDeviceStatus } from '../lib/status.js';
import {
    formatDeviceProperty,
    getDeviceProperty,
    getDeviceProperties,
    formatDeviceProperties,
} from '../lib/property.js';
import { createDeviceAPI } from '../lib/device-api.js';
import { configExists } from '../lib/config.js';
import {
    callDeviceResource,
    listDeviceResourcesWithSchemas,
    formatDeviceResourcesWithSchemas,
} from '../lib/resource.js';
import { getDevices } from '../lib/device.js';
import {
    setJsonMode,
    isJsonMode,
    printOk,
    printErr,
    createSpinner,
    classifyError,
} from '../lib/output.js';

function ensureConfigured() {
    if (!configExists()) {
        printErr('Not configured. Run thinr without parameters to set up.', { code: 'not_configured' });
    }
}

function applyJsonFlag(opts) {
    if (opts.json) setJsonMode(true);
}

// Walks up to the root program so subcommands can read `--user` regardless
// of nesting depth.
function getGlobalUser(cmd) {
    let root = cmd;
    while (root.parent) root = root.parent;
    return root.opts().user || null;
}

// Collect repeatable `-i key=value` pairs into a single object. Uses
// Commander's InvalidArgumentError so a bad value prints a clean
// "error: option … argument is invalid" line instead of a stack trace.
function collectInput(value, previous = {}) {
    const idx = value.indexOf('=');
    if (idx === -1) throw new InvalidArgumentError('must be key=value');
    return { ...previous, [value.slice(0, idx)]: value.slice(idx + 1) };
}

/**
 * `thinr device <subcommand> [<deviceId>] …` — all device-scoped actions
 * as proper Commander subcommands. Most subcommands declare `<deviceId>`
 * as their first positional so help, option parsing and validation are
 * autogenerated per-action; `list` is the exception (it operates on the
 * fleet, not a single device).
 */
export function deviceCommand(program) {
    const device = program
        .command('device')
        .description('Device commands (subcommand-first: thinr device <action> <deviceId>)');

    // ─── List / search ─────────────────────────────────────────────────────
    device
        .command('list [pattern]')
        .description('List devices, optionally filtered by name/id pattern (case-insensitive regex)')
        .option('-j, --json', 'Output as JSON')
        .action(async (pattern, opts, cmd) => {
            applyJsonFlag(opts);
            ensureConfigured();
            const user = getGlobalUser(cmd);
            const filter = pattern ? { name: pattern } : {};
            const label = pattern
                ? `Searching devices matching "${pattern}"...`
                : 'Fetching devices...';
            const spinner = createSpinner(label).start();
            try {
                const devices = await getDevices(filter, user);
                spinner.succeed(`Found ${devices.length} device(s)`);
                if (isJsonMode()) {
                    printOk(devices);
                } else {
                    for (const d of devices) {
                        const online = d.connection?.active ? chalk.green('online ') : chalk.gray('offline');
                        const name = d.name ? chalk.gray(` (${d.name})`) : '';
                        console.log(`  ${online}  ${chalk.bold(d.device)}${name}`);
                    }
                }
            } catch (error) {
                spinner.fail('Failed to list devices');
                const { message, code } = classifyError(error);
                printErr(message, { code });
            }
        });

    // Wrapper for the proxy / console handlers, which now return a Promise
    // that resolves with an exit code or rejects with a tagged Error
    // (instead of calling process.exit themselves).
    const runInteractive = async (fn) => {
        try {
            const exitCode = await fn();
            process.exit(exitCode ?? 0);
        } catch (error) {
            const { message, code } = classifyError(error);
            console.error(chalk.red(`Error [${code}]: ${message}`));
            process.exit(1);
        }
    };

    // ─── Proxies ───────────────────────────────────────────────────────────
    device
        .command('tcp <deviceId> [target]')
        .description('Create a TCP proxy (no TLS). Default target: 22.')
        .option('-p, --port <port>', 'Local port to use (default: random)')
        .action((deviceId, target, opts) => runInteractive(() => {
            ensureConfigured();
            return handleProxyAction(deviceId, 'tcp', target, { port: opts.port });
        }));

    device
        .command('tls <deviceId> [target]')
        .description('Create a TLS proxy. Default target: 443.')
        .option('-p, --port <port>', 'Local port to use (default: random)')
        .action((deviceId, target, opts) => runInteractive(() => {
            ensureConfigured();
            return handleProxyAction(deviceId, 'tls', target, { port: opts.port });
        }));

    device
        .command('http <deviceId> [target]')
        .description('Create an HTTP proxy. Default target: 80.')
        .option('-p, --port <port>', 'Local port to use (default: random)')
        .option('--no-open', 'Do not open the browser')
        .action((deviceId, target, opts) => runInteractive(() => {
            ensureConfigured();
            return handleProxyAction(deviceId, 'http', target, {
                port: opts.port,
                openBrowser: opts.open,
            });
        }));

    // ─── Console ───────────────────────────────────────────────────────────
    device
        .command('console <deviceId>')
        .description('Open an interactive terminal on the device')
        .action((deviceId) => runInteractive(() => {
            ensureConfigured();
            return connectToDeviceConsole(deviceId);
        }));

    // ─── Status ────────────────────────────────────────────────────────────
    device
        .command('status <deviceId>')
        .description('Check device status and stats')
        .option('-j, --json', 'Output as JSON')
        .action(async (deviceId, opts) => {
            applyJsonFlag(opts);
            ensureConfigured();
            const spinner = createSpinner(`Checking status of ${deviceId}...`).start();
            try {
                const status = await getDeviceStatus(deviceId);
                spinner.succeed(`Device ${deviceId} found`);
                if (isJsonMode()) printOk(status);
                else console.log(formatDeviceStatus(deviceId, status));
            } catch (error) {
                spinner.fail('Status check failed');
                const { message, code } = classifyError(error);
                printErr(message, { code });
            }
        });

    // ─── Properties ────────────────────────────────────────────────────────
    device
        .command('property <deviceId> [propertyId]')
        .description('List device properties, or read one by ID')
        .option('-j, --json', 'Output as JSON')
        .option('-f, --field <field>', 'Extract a sub-field (dot path, e.g. data.value)')
        .action(async (deviceId, propertyId, opts) => {
            applyJsonFlag(opts);
            ensureConfigured();
            if (!propertyId) {
                const spinner = createSpinner(`Getting properties for ${deviceId}...`).start();
                try {
                    const result = await getDeviceProperties(deviceId);
                    spinner.succeed(`Properties for ${deviceId} retrieved successfully`);
                    if (isJsonMode()) printOk(result);
                    else console.log(formatDeviceProperties(deviceId, result));
                } catch (error) {
                    spinner.fail('Property retrieval failed');
                    const { message, code } = classifyError(error);
                    printErr(message, { code });
                }
                return;
            }
            const spinner = createSpinner(`Retrieving property for ${deviceId}...`).start();
            try {
                const property = await getDeviceProperty(deviceId, propertyId);
                spinner.succeed(`Property ${propertyId} for ${deviceId} found`);
                const value = opts.field
                    ? opts.field.split('.').reduce((obj, key) => obj && obj[key], property)
                    : property;
                if (isJsonMode()) printOk(value);
                else if (opts.field) console.log(value);
                else console.log(formatDeviceProperty(deviceId, propertyId, property));
            } catch (error) {
                spinner.fail('Property retrieval failed');
                const { message, code } = classifyError(error);
                printErr(message, { code });
            }
        });

    // ─── Resources ─────────────────────────────────────────────────────────
    device
        .command('resource <deviceId> [resource]')
        .description('List device resources, or call one by name')
        .option('-j, --json', 'Output as JSON')
        .option('-f, --field <field>', 'Extract a sub-field from the result (dot path)')
        .option('-i, --input <key=value>', 'Resource input (repeatable)', collectInput, {})
        .action(async (deviceId, resource, opts) => {
            applyJsonFlag(opts);
            ensureConfigured();
            if (!resource) {
                const spinner = createSpinner(`Getting resources for ${deviceId}...`).start();
                try {
                    const entries = await listDeviceResourcesWithSchemas(deviceId);
                    spinner.succeed(`Successfully retrieved resources for ${deviceId}`);
                    if (isJsonMode()) printOk(entries);
                    else console.log(formatDeviceResourcesWithSchemas(deviceId, entries));
                } catch (error) {
                    spinner.fail('Resource retrieval failed');
                    const { message, code } = classifyError(error);
                    printErr(message, { code });
                }
                return;
            }
            const spinner = createSpinner(`Calling resource ${resource} for ${deviceId}...`).start();
            try {
                const result = await callDeviceResource(deviceId, resource, opts.input);
                spinner.succeed(`Resource ${resource} returned successfully for ${deviceId}`);
                const value = opts.field
                    ? opts.field.split('.').reduce((obj, key) => obj && obj[key], result)
                    : result;
                if (isJsonMode()) printOk(value);
                else console.log(value);
            } catch (error) {
                spinner.fail('Resource call failed');
                const { message, code } = classifyError(error);
                printErr(message, { code });
            }
        });

    // ─── Exec ──────────────────────────────────────────────────────────────
    device
        .command('exec <deviceId> <command...>')
        .description('Execute a shell command on the device')
        .option('-j, --json', 'Buffer stdout/stderr and emit a single JSON envelope')
        .option('--legacy', 'Use the non-streaming one-shot API (older agents)')
        .action(async (deviceId, commandParts, opts, cmd) => {
            applyJsonFlag(opts);
            ensureConfigured();
            const user = getGlobalUser(cmd);
            const commandStr = commandParts.join(' ');
            try {
                const api = createDeviceAPI(deviceId, { user });
                if (isJsonMode()) {
                    let stdout = '';
                    let stderr = '';
                    const { exitCode, timedOut, cancelled } = await api.execStream(commandStr, {
                        onStdout: (s) => { stdout += s; },
                        onStderr: (s) => { stderr += s; },
                    });
                    if (cancelled) printErr('Interrupted', { code: 'cancelled', exitCode: 130 });
                    if (timedOut) printErr('Command timed out on the device', { code: 'timeout' });
                    printOk({ stdout, stderr, exitCode: exitCode ?? null });
                    process.exit(exitCode ?? 1);
                }
                if (opts.legacy) {
                    const result = await api.exec(commandStr, 120);
                    if (result.stdout) process.stdout.write(result.stdout);
                    if (result.stderr) process.stderr.write(result.stderr);
                    process.exit(result.retcode || 0);
                }
                let cancelFn = null;
                const onSigint = () => cancelFn?.();
                process.on('SIGINT', onSigint);
                const { exitCode, timedOut, cancelled } = await api.execStream(commandStr, {
                    onStdout: (s) => process.stdout.write(s),
                    onStderr: (s) => process.stderr.write(s),
                    onCancel: (fn) => { cancelFn = fn; },
                    stdin: process.stdin,
                });
                process.off('SIGINT', onSigint);
                if (timedOut) {
                    console.error(chalk.red('\nError: command timed out on the device.'));
                }
                if (cancelled) {
                    console.error(chalk.yellow('\n[interrupted]'));
                    process.exit(130);
                }
                process.exit(exitCode ?? 1);
            } catch (error) {
                const { message, code } = classifyError(error);
                if (isJsonMode()) printErr(message, { code });
                // Human path: prefix `[code]` matches the MCP error format
                // and the rest of the CLI; the response dump only surfaces
                // when the failure carries an HTTP body.
                console.error(chalk.red(`Error [${code}]: ${message}`));
                if (error.response) {
                    console.error(chalk.red(`Status: ${error.response.status}`));
                    console.error(chalk.red(`Body: ${JSON.stringify(error.response.data)}`));
                }
                process.exit(1);
            }
        });

    // ─── Update ────────────────────────────────────────────────────────────
    const update = device
        .command('update')
        .description('Check for or apply agent updates');

    const runUpdate = async (action, deviceId, opts, cmd) => {
        applyJsonFlag(opts);
        ensureConfigured();
        const user = getGlobalUser(cmd);
        const channel = opts.channel || 'latest';
        const label = action === 'check' ? 'Checking for updates' : 'Applying update';
        const spinner = createSpinner(`${label} on ${deviceId}...`).start();
        try {
            const api = createDeviceAPI(deviceId, { user });
            const timeout = action === 'apply' ? 300000 : 30000;
            const result = await api.callResource('update', { action, channel }, { timeout });
            spinner.succeed(`${label} finished`);
            if (isJsonMode()) {
                printOk(result);
            } else if (result && typeof result === 'object') {
                if (result.current) console.log(`  current: ${chalk.bold(result.current)}`);
                if (result.latest)  console.log(`  latest:  ${chalk.bold(result.latest)}`);
                if (result.arch)    console.log(`  arch:    ${result.arch}`);
                if (result.status)  console.log(`  status:  ${chalk.cyan(result.status)}`);
                if (result.message) console.log(`  message: ${result.message}`);
            } else {
                console.log(result);
            }
        } catch (error) {
            spinner.fail(`${label} failed`);
            const { message, code } = classifyError(error);
            printErr(message, { code });
        }
    };

    update
        .command('check <deviceId>')
        .description('Check if an agent update is available')
        .option('-j, --json', 'Output as JSON')
        .option('--channel <name>', 'Update channel (default: latest)')
        .action((deviceId, opts, cmd) => runUpdate('check', deviceId, opts, cmd));

    update
        .command('apply <deviceId>')
        .description('Apply an agent update')
        .option('-j, --json', 'Output as JSON')
        .option('--channel <name>', 'Update channel (default: latest)')
        .action((deviceId, opts, cmd) => runUpdate('apply', deviceId, opts, cmd));

}
