// @ts-check
import { registerListCommand } from './list.js';
import { registerProxyCommands } from './proxy.js';
import { registerConsoleCommand } from './console.js';
import { registerStatusCommand } from './status.js';
import { registerPropertyCommand } from './property.js';
import { registerResourceCommand } from './resource.js';
import { registerExecCommand } from './exec.js';
import { registerUpdateCommand } from './update.js';
import { registerCpCommand } from './cp.js';

/**
 * `thinr device <subcommand> [<deviceId>] …` — all device-scoped actions
 * as proper Commander subcommands. Most subcommands declare `<deviceId>`
 * as their first positional so help, option parsing and validation are
 * autogenerated per-action; `list` is the exception (it operates on the
 * fleet, not a single device).
 */
export function deviceCommand(program) {
    const device = program
        .command('device')
        .description('Device commands (subcommand-first: thinr device <action> <deviceId>)');

    registerListCommand(device);
    registerProxyCommands(device);
    registerConsoleCommand(device);
    registerStatusCommand(device);
    registerPropertyCommand(device);
    registerResourceCommand(device);
    registerExecCommand(device);
    registerUpdateCommand(device);
    registerCpCommand(device);
}
